src/Entity/Note.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Note
 *
 * @ORM\Table(name="note", indexes={@ORM\Index(name="fk_Note_User1_idx", columns={"idBeer"}), @ORM\Index(name="fk_Note_Beer1_idx", columns={"id_user"})})
 * @ORM\Entity
 */
class Note
{
    /**
     * @var int
     *
     * @ORM\Column(name="idNote", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idnote;

    /**
     * @var int
     *
     * @ORM\Column(name="value", type="integer", nullable=false)
     */
    private $value;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="date", type="date", nullable=true)
     */
    private $date;

    /**
     * @var string|null
     *
     * @ORM\Column(name="comment", type="string", length=1000, nullable=true)
     */
    private $comment;

    /**
     * @var \Beer
     *
     * @ORM\ManyToOne(targetEntity="Beer")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idBeer", referencedColumnName="idBeer")
     * })
     */
    private $idbeer;

    /**
     * @var \User
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_user", referencedColumnName="id_user")
     * })
     */
    private $id_user;

    public function getIdnote(): ?int
    {
        return $this->idnote;
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(int $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getBeer(): ?Beer
    {
        return $this->idbeer;
    }

    public function setBeer(?Beer $id_user): self
    {
        $this->idbeer = $id_user;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->id_user;
    }

    public function setUser(?User $idbeer): self
    {
        $this->id_user = $idbeer;

        return $this;
    }


}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}DailyBeer
			{% endblock %}
		</title>
		<link
		rel="icon" href="{{ asset('/imgs/site/icondailybeer.png') }}">
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		<link href="{{asset('css/beer_anim.css')}}" rel="stylesheet">

		<link href="{{asset('bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
		<link href="{{asset('css/base.css')}}" rel="stylesheet">
		<script src="{{asset('bootstrap/js/bootstrap.bundle.min.js')}}"></script>
		<script src="https://code.iconify.design/2/2.1.2/iconify.min.js"></script>
		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}
	</head>
	<body>
		<header>
			<!-- <div id="glass">
												  <div id="beer"></div>
												</div>
												<div id="poignet"></div>
												<div id="mousse_1"></div>
												<div id="mousse_2"></div>
												<div id="mousse_3"></div>
												<div id="mousse_4"></div>
												<div id="mousse_5"></div>
												<div id="mousse_volante"></div>
												<div id="mousse_interieur"></div>
												<div id="mousse_interieur_2"></div>
												<div id="mousse_interieur_3"></div>
												<div id="mousse_interieur_4"></div> -->
			<nav class="navbar  fixed-top ">

				<a href="/"><img src="{{ asset('/imgs/site/banner.png') }}" height="100px"></a>
				<div></div>

				<ul class="navbar-nav ">
					<li class="nav-item">
						<div class="btn-group m-2" role="group" aria-label="Basic outlined example">
							<button type="button" class="btn btn-outline-primary boutonNav border-warning " onclick="window.location.href = '/beer';">Gestion Bière</button>
							<button type="button" class="btn btn-outline-primary boutonNav border-warning " onclick="window.location.href = '/company';">Gestion Brasserie</button>
							<form class="d-flex m-2">
								<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
							</form>
							{% if app.user %}
								<button type="button" class="btn  btn-outline-primary boutonNav border-warning" onclick="window.location.href = '/profil/{{app.user.id_user}}';">
									<img src="{{asset('/imgs/site/UserPicture.png')}}" class="img-fluid" alt="..." style="height: 50px;">
									{{ app.user.pseudo }}</button>


								<button type="button" class="btn btn-outline-primary boutonNav border-warning" onclick="window.location.href = '/logout';">Déconnexion</button>
							{% else %}
								<button type="button" class="btn btn-outline-primary boutonNav border-warning" onclick="window.location.href = '/login';">Connexion</button>
								<button type="button" class="btn btn-outline-primary boutonNav border-warning" onclick="window.location.href = '/inscription';">Inscription</button>
							{% endif %}
						</div>
					</li>


				</ul>

			</nav>
			<br>
			<br>
			<br>
			<br>

		</header>
		{% block body %}{% endblock %}
	</body>
</html>